sudo: false

language: node_js

node_js:
  - "8"

cache:
  directories:
    - node_modules

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - npm i -g npm@latest

install:
  - npm i

script:
  - npm run lint
  - npm run build
  - npm run build:npm

git:
  depth: 1
